### PR TITLE
Add Grey and Black Bridge

### PR DESCRIPTION
**Pull request by danirabbit**
- [x] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [x] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [ ] At least 3200×1800 px
- [x] I've added the artist metadata using `exiftool`

## Why it should be included:
Something a bit different :)

It is slightly smaller than our minimum at 3000x2000

Unsplash license: https://unsplash.com/photos/raNGlrn5JRI

## Screenshot(s) of it in Pantheon on elementary OS:
Screenshot from 2022-10-13 10 20 59

### CODE REVIEW

**Comment by micahilbery** [comment]
If the speed limit sign can be convincingly edited out this would be perfect but that sign is a real bummer.

**Comment by 1280px** [comment]
The photo is also a little skewed to the left, and needs to be rotated for around 0.15-0.20 deg. 

Is this PR still is power? I think it could work very nicely as 7.1 default wallpaper

**Comment by 1280px** [comment]
Also, I found the 2 similar images that might work better compositionally:
https://unsplash.com/photos/n2FNx6UH7l0 (my favourite, also has larger resolution)
https://unsplash.com/photos/fY97QRPAGeU
They all need to be re-cropped and photocorrected for a bit but are actually hi-res enough to still look good after being cropped.

**Comment by danirabbit** [comment]
Gonna close this since it has issues and I don't think anyone is available/interesting to resolve them

**Comment by 1280px** [comment]
I could work on it, but first what about the suggested similar images above?

> https://unsplash.com/photos/n2FNx6UH7l0
> https://unsplash.com/photos/fY97QRPAGeU

img1_clutter img1_noclutter

They both are large enough to comply with minimal size restriction and pass all the other requirements, and work better compositionally while still being minimalistic. They only work they need is cropping and maybe a bit of sharpening. I can open a separate PR if someone finds any of them nice too

**Pull request closed without merging**
