### PR TITLE
Delete leigh-kendell-581.jpg

### PR DESCRIPTION
**Pull request by danrabbit**
This is the last kind of grainy, desaturated wall we're shipping

### CODE REVIEW

**Comment by cassidyjames** [comment]
Noooo I love this one, lol. It definitely doesn't look grainy or desaturated here on my 4K Dell display… I'll have to poke at it on other hardware to really judge. But it's always been one of my favorite colorful wallpapers.

**Comment by danrabbit** [comment]
I dunno I guess the black point is like really bright here

**Comment by GammaGames** [comment]
I do like this one, but it is really washed out. I wonder if there's a similar wallpaper with better colors it could be replaced with

**Comment by danrabbit** [comment]
Closing since it seems like other people like this wallpaper

**Pull request closed without merging**
