### PR TITLE
Desk Plants photo

### PR DESCRIPTION
**Pull request by BWPanda**
- [ ] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [ ] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [x] I've updated `debian/copyright` with:
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`
## Why it should be included:
Something a bit different...? Minimal.

## Screenshot(s) of it in Pantheon on elementary OS:
Desk Plants

Original photo: https://www.pexels.com/photo/three-green-assorted-plants-in-white-ceramic-pots-776656/

### CODE REVIEW

**Comment by BWPanda** [comment]
Copyright PR: https://github.com/elementary/wallpapers/pull/114

**Comment by lainsce** [comment]
Real screenshot of it under elementary OS:

desk-plants

**Comment by micahilbery** [comment]
I'm a :-1: on this one, there's nothing really wrong with it it's just kinda boring.

**Comment by cassidyjames** [comment]
I'm indifferent, but leaning toward :-1:. It's a fine photo, but the subject doesn't really fit in with elementary OS to me.

I _do_ like that it's a bright wallpaper that makes the panel fg go dark.

**Pull request closed without merging**
