### PR TITLE
Added Black & White Julia Craice Wallpaper

### PR DESCRIPTION
**Pull request by lainsce**
- [x] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [x] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [x] I've updated `debian/copyright` with:
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`
## Why it should be included:
It's the first fully black & white wallpaper for inclusion in elementary OS that isn't busy, edited from the original at https://unsplash.com/photos/jCHgHnRH4So

## Screenshot(s) of it in Pantheon on elementary OS:
Screenshot from 2019-09-19 23 43 56

### CODE REVIEW

**Comment by cassidyjames** [comment]
At a glance, I really like this. It's different and seems to compliment Pantheon well.

**Comment by cassidyjames** [comment]
Slightly more typical aspect ratio:

Screenshot from 2019-09-26 20-28-41@2x

**Comment by cassidyjames** [comment]
One critique might be that the top-left corner is a little dark, leading to worse contrast with the panel. Especially on 16:9 ratio.

**Comment by lainsce** [comment]
A bit of soft black to transparent gradient at the top to make it force the white icons would be ideal then?

**Comment by cassidyjames** [comment]
@lainsce I was actually thinking the opposite; the top looks nice being light, but the top-left was just a _little_ too dark. Now you've gone and made all of the top dark which kinda works, but I don't like how it looks as much :stuck_out_tongue:

**Comment by lainsce** [comment]
I mean, I think the centerpiece of the only black & white wallpaper in the set would be tasteful to have the default wingpanel look which is transparent + white icons, don't you agree? Besides, the contrast with a maximized app is amazing this way. :smile:

**Comment by lainsce** [comment]
Yin-yang'd wallpaper:

Screenshot from 2019-09-27 00 49 32

**Pull request merged**
