### PR TITLE
Light house by William bout 

### PR DESCRIPTION
**Pull request by MrPotatoBobx**
- [x] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [x] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [x] I've updated `debian/copyright` with(#145):
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`
## Why it should be included:
I think it really looks nice no matter what theme you have on, its kind of a hybrid between dark and light pictures, i also really like how the blues look

## Screenshot(s) of it in Pantheon on elementary OS:
desktop
Pantheon desktop with lighthouse wallpaper

unmaximized window open
Pantheon desktop with unmaximized window open

link: https://unsplash.com/photos/7cdFZmLlWOM
theres also a lighter version(**NOT** included in pull request): https://unsplash.com/photos/uFNElcqa6D0

### CODE REVIEW

**Comment by jtagcat** [comment]
I honestly prefer the lighter version.

**Comment by jtagcat** [comment]
Rename the file so there isn't a space before `.jpg`.

**Comment by MrPotatoBobx** [comment]
> Could the file be renamed, so there isn't a space before `.jpg`?

my bad, ill make sure thats fixed

**Comment by MrPotatoBobx** [comment]
> I honestly prefer the lighter version.

I mean, we could include both, but it would be a bit repetitive

**Comment by jtagcat** [comment]
> > I honestly prefer the lighter version.
> 
> I mean, we could include both, but it would be a bit repetitive

Indeed. Thoughts on day/night? Though the difference probably isn't significant enough.

**Comment by danrabbit** [comment]
Thanks for submitting! Would love other opinions from @elementary/ux 

I think I'm kind of :-1: on this one. I'm not a huge fan of long exposure shots when there is water or clouds. It tends to look really muddy in those areas that are moving. And I'm not sure the light coming from the lighthouse directly to the viewer is very nice.

**Comment by cassidyjames** [comment]
I agree with @danrabbit, not the biggest fan of this one and the long exposure.

**Pull request closed without merging**
