### PR TITLE
Morskie Oko ferns

### PR DESCRIPTION
**Pull request by aljelly**
- [x] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [x] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [x] I've updated `debian/copyright` with:
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`
## Why it should be included:
It's nice and colourful. It doesn't show the bar at the top.

## Screenshot(s) of it in Pantheon on elementary OS:
screenshot from 2018-08-15 18-11-00

### CODE REVIEW

**Comment by cassidyjames** [comment]
@aljelly thanks for this submission! I'm personally :-1: because of the extreme blur on the right side contrasting with the background leaves on the left; it seems really imbalanced to me.

**Comment by aljelly** [comment]
@cassidyjames There is also another fern photo by the same photographer with no blur:

screenshot from 2018-08-15 18-11-00

**Comment by danrabbit** [comment]
@aljelly I'm interested in the version with no blur. Nice find :+1:

**Comment by aljelly** [comment]
OK, I've swapped the original photo for the one with no blur.

**Pull request merged**
