### PR TITLE
Northern Lights photo

### PR DESCRIPTION
**Pull request by BWPanda**
- [ ] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [ ] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [x] I've updated `debian/copyright` with:
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`
## Why it should be included:
We don't have any Northern Lights photos yet :wink: 

## Screenshot(s) of it in Pantheon on elementary OS:
Northern Lights

Original photo: https://pixabay.com/photos/nature-forest-night-sky-4790694/

### CODE REVIEW

**Comment by BWPanda** [comment]
PR for copyright here: https://github.com/elementary/wallpapers/pull/108

**Comment by lainsce** [comment]
Real screenshot of it under elementary OS:

northern-lights

**Comment by micahilbery** [comment]
I'm a :-1: on this one It almost looks like the trees were added after the fact. they feel weirdly sharp compared to the soft noisy sky.

**Comment by cassidyjames** [comment]
Agreed with @micahilbery

**Pull request closed without merging**
