### PR TITLE
Add Brown Architecture photo.

### PR DESCRIPTION
**Pull request by BWPanda**
- [ ] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [ ] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [x] I've updated `debian/copyright` with:
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`
## Why it should be included:
Architecture (I read that you're wanting more of those...?)

## Screenshot(s) of it in Pantheon on elementary OS:
Brown Architecture

Original photo: https://unsplash.com/photos/aQcE3gDSSTY

### CODE REVIEW

**Comment by BWPanda** [comment]
Copyright PR: https://github.com/elementary/wallpapers/pull/112

**Comment by Exalm** [comment]
Umm, what's up with the panel and dock?

**Comment by BWPanda** [comment]
@Exalm I don't have Elementary OS (yet) so I had to fudge this using https://github.com/elementary/wallpapers#for-reference

**Comment by Exalm** [comment]
That's not enough though. The top panel changes style based on the wallpaper, you can't just "guess" that.

**Comment by lainsce** [comment]
Real screenshot of it under elementary OS:

brown-architecture

**Comment by danrabbit** [comment]
Interesting photo but I'm gonna say -1 since it triggers the panel to become opaque. Thanks for the submission!

**Pull request closed without merging**
