### PR TITLE
Add Scott Riley jelly wallpaper

### PR DESCRIPTION
**Pull request by cassidyjames**
- [x] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [x] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [x] I've updated `debian/copyright` with:
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`

## Why it should be included:

It's a nice dark wallpaper that @danrabbit and I seemed to like

## Screenshot(s) of it in Pantheon on elementary OS:

Screenshot from 2019-12-02 21-58-12

Screenshot from 2019-12-02 21-58-29

### CODE REVIEW

**Comment by micahilbery** [comment]
I like the subject matter and the colors but it gets a little more noticeably grainy in the tentacles area. I really like the photo otherwise so if it doesn't bother anyone else I'm fine with it.

**Comment by cassidyjames** [comment]
I hadn't noticed the grain before, but I definitely see it. I like the wallpaper in general but if it's too grainy I'm fine to also find some better dark wallpapers.

**Comment by BWPanda** [comment]
Something like this instead maybe...? https://www.pexels.com/photo/closeup-photo-of-jellyfish-685329/

**Comment by jtagcat** [comment]
> Something like this instead maybe...? https://www.pexels.com/photo/closeup-photo-of-jellyfish-685329/
> 
> 

That's too intense for me.

**Comment by danrabbit** [comment]
Since this has several downvotes, I'm inclined to close it. I think an undersea paper is a cool direction, but I'm not sure this one is it

**Pull request closed without merging**
