### PR TITLE
Add White Clouds

### PR DESCRIPTION
**Pull request by cassidyjames**
And edit I made based on https://unsplash.com/photos/rOAFxjnfRgg

- [x] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [x] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [x] I've updated `debian/copyright` with: (#142)
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`

## Why it should be included:

It's a throwback to the Jupiter wallpaper but less busy and higher res

## Screenshot(s) of it in Pantheon on elementary OS:

Screenshot from 2021-04-14 13-23-47

### CODE REVIEW

**Comment by meisenzahl** [comment]
@cassidyjames you may want to set the accent color with the help of https://github.com/elementary/wallpapers/pull/140

**Comment by cassidyjames** [comment]
Hold up on this, I think I want to export a little higher quality because it has visible jpg artifacting.

@meisenzahl ah yeah will do.

**Comment by cassidyjames** [comment]
Hm, after staring at this for too long, the original image has some pretty aggressive JPG artifacting that will need to be cleaned up manually. Here's my working file if someone wanted to take a stab (warning: 75 MB Glimpse file): https://upload.cassidyjames.com/chuttersnap-rOAFxjnfRgg-unsplash-edit.xcf

**Comment by danrabbit** [comment]
I do like this, but I wonder if it's similar-but-not-quite-as-good as the yellow flower thingy by Martin Adams. I wonder if they're different enough?

**Comment by cassidyjames** [comment]
@danrabbit ah yeah they're both pretty flat lighter blue walls. I'm kind of indifferent at this point; I enjoy this one for nostalgia but don't feel super compelled to include it by default. :)

**Comment by cassidyjames** [comment]
I'm closing this as I don't feel inclined to try to correct the compression artifacts in the original.

**Pull request closed without merging**
