### PR TITLE
Wallpaper - Vieste Coast by Edoardo Brogiolo

### PR DESCRIPTION
**Pull request by edo0**
- [X] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [X] Looks good in Pantheon on elementary OS
  - [X] Not too distracting if a non-maximized window is open
  - [X] No text or logos
  - [X] No people
  - [X] At least 3200×1800 px
- [X] I've upated `debian/copyright` with:
  - [X] The name of the wallpaper and/or its original author
  - [X] A link to where it can be downloaded
  - [X] Included under the respective license section (or created a new one if appropriate)
- [X] I've added the artist metadata using `exiftool`
## Why it should be included:
Aesthetically pleasing as to what concerns subjects and colours.
The harmony and linearity of the horizon against the rage and irregularity of the crest of the waves.
## Screenshot(s) of it in Pantheon on elementary OS:
screenshot from 2017-12-30 15-04-03
screenshot from 2017-12-30 15-02-39

### CODE REVIEW

**Comment by farid-fari** [comment]
I think the white on the bottom kind of makes the dock hard to read...

**Comment by edo0** [comment]
Whereas it's true that the dock will partly blend with the white foam, I think that clarity of the icons will not suffer from that, and if anything might even be enhanced.

**Comment by cassidyjames** [comment]
Screenshot with default settings

screenshot from 2018-04-22 14 08 14

I think I agree that the white at the bottom is pretty busy and conflicts with the dock.

**Comment by danrabbit** [comment]
Hey thanks for your submission! I'm going to close this PR for the reasons Cassidy cited

**Pull request closed without merging**
