### PR TITLE
Compatible wallpapers

### PR DESCRIPTION
**Pull request by snwh**
I'm tracking down original authors of removed wallpapers (those who I can find) to see which we can re-add.
- [ ] [Horseshoe Bend Sunset](http://www.flickr.com/photos/24046097@N00/4418745305)
- [ ] [Lake Tahoe Colors](https://www.flickr.com/photos/romainguy/4247339382/)

- [Water Lilly](http://islingt0ner.deviantart.com/art/Water-Lily-165791833) ([original](https://www.flickr.com/photos/tanaka_juuyoh/4462929191/) is cc-by) :+1:  
- Living Stones ([original](https://www.flickr.com/photos/andesine/5560436312) is cc-by) :+1:

- [The Coast](http://skyofca.deviantart.com/art/The-Coast-197763965) :-1: 
  - original from stock photo company
  - license incompatible: http://www.freeimages.com/photo/the-coast-1246367
- [Leaves](http://emats.deviantart.com/art/Leaves-Wallpaper-100824718)  :-1: 
  - link in `copyright` was not original author
  - license unclear
  - original author unreachable; 404s (http://emats.deviantart.com/art/Golden-Leaves-100740659)
- [Urban Dream](http://delta909.deviantart.com/art/UrbanDream-190307415) :-1: 
  - license unclear
  - original image copyrighted 
  - original author unreachable

### CODE REVIEW

**Comment by cassidyjames** [comment]
For the record, Romain Guy is open to us using his photos but we want to clarify the licensing.

https://twitter.com/romainguy/status/880441822870360064

**Comment by snwh** [comment]
@cassidyjames yep, I'm waiting on his response :)

**Comment by codygarver** [comment]
Can `Living Stones` not return, @dahenson got a complaint from his wife about it.

**Comment by codygarver** [comment]
`Water Lily` has been restored in master, `Living Stones` is rejected.

The remaining wallpapers, `Lake Tahoe Colors` and `Horseshoe Bend Sunset` have not been followed up on so I'm closing this PR.

**Pull request closed without merging**
