### PR TITLE
Sunset Tree photo

### PR DESCRIPTION
**Pull request by BWPanda**
- [ ] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [ ] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [x] I've updated `debian/copyright` with:
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`
## Why it should be included:
It has a purple colour-scheme (different from other photos), a single point of focus off-center and smooth gradients.

## Screenshot(s) of it in Pantheon on elementary OS:
Sunset tree

Original photo: https://pixabay.com/photos/sunset-tree-water-silhouette-1373171/

### CODE REVIEW

**Comment by BWPanda** [comment]
Here's the PR for copyright changes: https://github.com/elementary/wallpapers/pull/106

**Comment by lainsce** [comment]
Real screenshot of it under elementary OS:

sunset_tree

**Comment by micahilbery** [comment]
I really like the colors in this one but the composition feels a little empty and boring so idk. I could go either way.

**Comment by cassidyjames** [comment]
@micahilbery I'm kind of in the same boat. I say let's sit on it and see if we can find a better purple wallpaper. :smile:

**Comment by jtagcat** [comment]
> @micahilbery I'm kind of in the same boat. I say let's sit on it and see if we can find a better purple wallpaper. smile

There must be pink/purple everywhere. Many parents raise girls surrounded with much pink. They and the children will choose pink everywhere. The world is strange. :upside_down_face:

**Comment by danrabbit** [comment]
This is, IMO, really close to Sunset By The Pier. So I'm inclined to close this since there doesn't seem to be absolute love for it :)

Thanks for the submission!

**Pull request closed without merging**
