### PR TITLE
Snow-capped mountain

### PR DESCRIPTION
**Pull request by BWPanda**
- [x] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [x] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [ ] I've updated `debian/copyright` with:
  - [ ] The name of the wallpaper and/or its original author
  - [ ] A link to where it can be downloaded
  - [ ] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`
## Why it should be included:
A visually-striking photo with good areas top and bottom for icons, etc.

## Screenshot(s) of it in Pantheon on elementary OS:
Snow-capped

Image from: https://www.pexels.com/photo/photo-of-snow-capped-mountain-during-evening-2440024/

### CODE REVIEW

**Comment by danrabbit** [comment]
This is a pretty cool wallpaper! I like that the stars don't trigger the panel opacity.

I feel like it's a significantly different view of Half Dome from the macOS Yosemite wallpaper and the night time and season make it a pretty different color palette, so I'm not too concerned about that whole thing.

I also like it more than some of the other mountain ones we currently have in there. I think I'd drop Luca Bravo in favor of this, just so we don't have too many mountains.

Thoughts @cassidyjames ?

**Comment by cassidyjames** [comment]
@danrabbit I also like it and was double-checking licensing to make sure we're in the clear. It appears to be the original and appears that Pexels has an almost-identical license to Unsplash so we should be good.

I really like the super different color palette in Luca Bravo. I think I'd be more willing to drop Ryan Schroeder since it's also a very blue + mountain wallpaper.

**Comment by danrabbit** [comment]
Yeah I just kinda don’t care for Luca Bravo that much, but I’ fine with trading Ryan Schroeder

**Comment by cassidyjames** [comment]
I will follow-up with a PR to drop Ryan Schroeder and one to update the debian files.

**Comment by BWPanda** [comment]
Woot! Thanks guys 😊

**Comment by Exalm** [comment]
@cassidyjames you might want to re-check the panel, the screenshot is not a screenshot. :/

https://github.com/elementary/wallpapers/pull/111#issuecomment-615242920

**Comment by lainsce** [comment]
Real screenshot:

snow-capped-mountain

**Comment by cassidyjames** [comment]
@Exalm I tested it locally of course. 😛

**Pull request merged**
