### PR TITLE
Adding a photo

### PR DESCRIPTION
**Pull request by acagastya**
I have added a photo to wallpapers, which is available for commercial use. Screenshot <https://twitter.com/acagastya/status/831305881312751617>

### CODE REVIEW

**Comment by fabianthoma** [comment]
@danrabbit can you review this please?

**Comment by cassidyjames** [comment]
What it looks like in Pantheon, for reference. 
image

**Comment by danrabbit** [comment]
I'm kinda -1 on this one. The colors are very dark and desaturated

**Comment by acagastya** [comment]
I am pretty sure the same applies to the default wallpaper Loki uses. Anyways, thanks for your time!

**Pull request closed without merging**
