### PR TITLE
Add 'Lamp post on dock'.

### PR DESCRIPTION
**Pull request by BWPanda**
- [ ] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [ ] Looks good in Pantheon on elementary OS
  - [ ] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [ ] I've updated `debian/copyright` with:
  - [ ] The name of the wallpaper and/or its original author
  - [ ] A link to where it can be downloaded
  - [ ] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`
## Why it should be included:
It looks nice, with a slightly darker tone.

## Screenshot(s) of it in Pantheon on elementary OS:
I couldn't do this I'm afraid as I'm not (yet) an Elementary OS user. I tried GIMPing it onto the examples in the README, but it looked yuk when I tried to remove the background from them...

### CODE REVIEW

**Comment by BWPanda** [comment]
I couldn't find a `debian/copyright` file, so couldn't do that bit I'm sorry. The image is from here though: https://unsplash.com/photos/0HFkStS9Gq0

**Comment by BWPanda** [comment]
Lamp post on dock

**Comment by cassidyjames** [comment]
Screenshot on elementary OS

Screenshot from 2020-04-14 14-15-10@2x

**Comment by BWPanda** [comment]
@cassidyjames Hmm, good point... Would it be worth cropping the image somewhat then? Something like this:

cropped-dock

If so, I'll update the PR.

As for the copyright file, I've created an issue for that here: https://github.com/elementary/wallpapers/issues/100

**Comment by danrabbit** [comment]
Hm yeah it's a bit similar to [Sunset by the pier](https://github.com/elementary/wallpapers/blob/master/backgrounds/Sunset%20by%20the%20Pier.jpg) as well. I think if we were to include this one, it would have to replace the other one

**Comment by BWPanda** [comment]
Based on the comments above (which make valid points), I'm going to close this PR (not centred and too similar to existing image).

**Pull request closed without merging**
