### PR TITLE
Added New Wallpaper

### PR DESCRIPTION
**Pull request by alvaroadlf**
- [x] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [x] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [x] No people
  - [x] At least 3200×1800 px
- [x] I've upated `debian/copyright` with:
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [x] I've added the artist metadata using `exiftool`
## Why it should be included:
A good photo of a beautiful landscape, has a very good resolution 4608x3456, without filters, made in the morning, with lots of light and lots of color.

## Screenshot(s) of it in Pantheon on elementary OS:
captura de pantalla de 2017-11-10 13-31-35

### CODE REVIEW

**Comment by alvaroadlf** [comment]
How long does it take to approve or deny it?

Thanks

**Comment by lewisgoddard** [comment]
@elementary/ux Anyone want to review this?

**Comment by alvaroadlf** [comment]
:'( no review

**Comment by btkostner** [comment]
Please be patient. @elementary/ux has a lot of changes to review, and wallpapers are low on the list of priorities. At some point someone from @elementary/ux will give this the thumbs up or down.

**Comment by danrabbit** [comment]
Hey thanks for your submission! Sorry it took a long time to look at. I'm going to say :-1: on this one just because of the solid panel. I'd prefer if default wallpapers all had a transparent panel

**Comment by cassidyjames** [comment]
I agree with @danrabbit here. It's a nice photo, but doesn't match what we're looking for in a wallpaper. Thanks for the submission!

**Pull request closed without merging**
