### PR TITLE
Change default to Odin Dark

### PR DESCRIPTION
**Pull request by danrabbit**
Should be merged with https://github.com/elementary/wallpapers/pull/165

Uses Meson to create the symlink instead of relying on packaging

### CODE REVIEW

**Comment by cassidyjames** [comment]
@danrabbit it looks like this branch will not update the existing symlink to the new wallpaper, but will omit creating the symlink if it already exists; is that intentional? In the past I believe we've ensured the symlink was updated so anyone who kept the default setting would get the new wallpaper automatically.

**Comment by danrabbit** [comment]
Ah no that isn't intentional. Thanks for catching that! I'll see if that's trivial to fix or else just revert that part

**Comment by danrabbit** [comment]
Alright, fixed. This now deletes existing symlinks instead of skipping

**Review by cassidyjames — APPROVED** [review]
I can confirm this does what it says!

**Pull request merged**
