### PR TITLE
new wallpaper - Ice mountains

### PR DESCRIPTION
**Pull request by brigazvi**
- [x] I've read and followed the [general guidelines](https://github.com/elementary/wallpapers#general-wallpaper-guidelines)
  - [x] Looks good in Pantheon on elementary OS
  - [x] Not too distracting if a non-maximized window is open
  - [x] No text or logos
  - [X] No people
  - [X] At least 3200×1800 px
- [x] I've upated `debian/copyright` with:
  - [x] The name of the wallpaper and/or its original author
  - [x] A link to where it can be downloaded
  - [x] Included under the respective license section (or created a new one if appropriate)
- [ ] I've added the artist metadata using `exiftool`
## Why it should be included:
   It's beautiful, and it meets all the requirements.

### CODE REVIEW

**Comment by cassidyjames** [comment]
screenshot from 2018-04-22 14 06 39

**Comment by liamdawson** [comment]
Is this only blocked by `exif` data?

**Comment by cassidyjames** [comment]
@liamdawson and it needs to be explicitly reviewed by @elementary/ux.

**Comment by cassidyjames** [comment]
Yeah, after re-reviewing my negatives outweigh my positives. It just feels fuzzy without a clear focal point.

**Pull request closed without merging**
