### PR TITLE
Accent color

### PR DESCRIPTION
**Pull request by meisenzahl**
Goes with https://github.com/elementary/settings-daemon/pull/25

### CODE REVIEW

**Comment by meisenzahl** [comment]
The accent color is now set as `AccentColor`. @cassidyjames do we want to possibly prefix that with `io.elementary.`?

**Comment by cassidyjames** [comment]
@meisenzahl I'm not super familiar with how XMP in EXIF works, but it sounds like it would be good to RDNN prefix it to avoid potential collisions?

**Comment by meisenzahl** [comment]
@cassidyjames Yes, exactly. Feel free to suggest what the attribute should be called.

**Comment by cassidyjames** [comment]
@meisenzahl io.elementary.AccentColor seems fine to me. Could we ensure we're matching this mapping, though? I think we're also generally moving to only use the cutesy food names in user strings and just use the color names anywhere for developers.

https://github.com/elementary/default-settings/commit/17d737ecc1fdd083127cbc290c49e3ad0563030b

**Comment by meisenzahl** [comment]
@cassidyjames I'll take a look to see if we can ensure we're matching this mapping.

What do you think about a command line tool that makes sure that when you add a new image attributes like author and accent color are set?

I can refactor to use the following colors:

```
0 = No Preference (currently assumes Blue)
1 = Red
2 = Orange
3 = Yellow
4 = Green
5 = Mint
6 = Blue
7 = Purple
8 = Pink
9 = Brown
10 = Gray
```

**Comment by cassidyjames** [comment]
@meisenzahl I would be open to is as long as it's simple enough to use and maintain. :)

**Comment by meisenzahl** [comment]
@cassidyjames ready for review. I hope I have set all colors correctly now :)

**Comment by cassidyjames** [comment]
@meisenzahl okay I talked this through with Dan to make sure this was a good approach, and we agree EXIF seems like a good fit. But what's the need for the command-line app? It seems that we have to copy-paste some commands from the README either way, so this seems like it might be over-complicated compared to just using exiftool directly.

**Comment by meisenzahl** [comment]
@cassidyjames with the command line application you can set the EXIF information, but you can also lint the files. The cli tool can also check if the provided accent color is a valid value.

I was not able to use `exif` to extract the custom `io.elementary.AccentColor` metadata. Maybe that works too, but I am not sure...

**Comment by cassidyjames** [comment]
@meisenzahl gotcha. I think for now, let's split the command line tool off into its own branch so we can discuss/debate it there—but I'm fine with the inclusion of the EXIF data here.

**Comment by meisenzahl** [comment]
I have cleaned up the PR so far. However, I am not sure how to write the `exiftool` commands and create the configuration file. Using RDNN makes things a bit more complicated 😅️

@cassidyjames shall we discuss how to proceed with adding and verifying the metadata in #140?

**Review by cassidyjames — APPROVED** [review]

**Pull request merged**
